inpu = open("teleport.in", "r")
a, b, x, y = inpu.readline().split(); a, b, x, y = int(a), int(b), int(x), int(y)
inpu.close()
diff1 = abs(x-a) + abs(y-b)
diff2 = abs(x-b) + abs(y-a)
diff3 = abs(a-b)
diff = min(diff1, diff2, diff3)
ou = open("teleport.out", "w")
ou.write(str(diff))
ou.close()
